### ISSUE TITLE
What do scores "<" and ">" mean?

### ISSUE THREAD

**Issue by andirayo** [tromp/fhourstones88#1]
Awesome piece of software!
Ikki just pointed this out to me and I have to say: I'm impressed.
Quick question: What do the scores "<" and ">" mean that are returned sometmes?

**Comment by tromp** [comment]
dear Andreas,

> Awesome piece of software!

Thanks!

> Ikki just pointed this out to me and I have to say: I'm impressed.
> Quick question: What do the scores "<" and ">" mean that are returned sometmes?

Those are inexact scores.
 < is either - or =.

> is either = or  +.

regards,
-John

**Comment by andirayo** [comment]
Ah, I see. Thanks for the clarification.
Also, sometimes, the process times out for me or, to be more precise, the program says 'Solving' but will not show any output after waiting for a minute.
Is this one of the situations where it would help to compile with the more memory-flag (DTRANSIZE,DLOCKSIZE)?
... or is the program simply not able to solve all situations?

As a question out of interest:
Why does the program work better if it gets compiled with the extra flags?
How does the program work? Does the book contain a list of situations with known outcome and tries to extrapolate certain situations from that list?

Anyways. Maybe, see you on the 9x9 board at LittleGolem, at some point! :)

**Comment by tromp** [comment]
hi Andreas,

> Also, sometimes, the process times out for me or, to be more precise, the program says 'Solving' but will not show any output after waiting for a minute.

Then it's still busy solving. There's no telling how long a search could take
before showing any output.

> Is this one of the situations where it would help to compile with the more memory-flag (DTRANSIZE,DLOCKSIZE)?

Obviously more memory will tend to speed up the search.

> ... or is the program simply not able to solve all situations?

It is. Some positions just take a lot more time than others.

> As a question out of interest:
> Why does the program work better if it gets compiled with the extra flags?

It has more computing resources available...

> How does the program work? Does the book contain a list of situations with known outcome and tries to extrapolate certain situations from that list?

It uses exhaustive alpha beta search with transposition tables.
Google those terms to find elaborate explanations.

regards,
-John

**Comment by tromp** [comment]
> Then it's still busy solving. There's no telling how long a search could take
> before showing any output.

Note that you can increase the amount of solved positions written to book
(and reported during search) by increasing BOOKWORK,
e.g. compile with -DBOOKWORK=28

-John

**Comment by andirayo** [comment]
Awesome, thanks for all your answers!
I will probably play around with it a little more in the weekend. :)
